create table public.publications (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  author bigint null,
  contributors json null,
  keywords json null,
  publication_date date null,
  abstract text null,
  research_center bigint null,
  link text null,
  textsearchable_contributors tsvector GENERATED ALWAYS as (
    json_to_tsvector(
      'english'::regconfig,
      contributors,
      '["string"]'::jsonb
    )
  ) STORED null,
  textsearchable_keywords tsvector GENERATED ALWAYS as (
    json_to_tsvector(
      'english'::regconfig,
      keywords,
      '["string"]'::jsonb
    )
  ) STORED null,
  pubmed_id text null,
  pubmed_central_id text null,
  grant_agency text null,
  is_open_access boolean null,
  constraint publications_pkey primary key (id),
  constraint publications_author_fkey foreign KEY (author) references authors (id),
  constraint publications_research_center_fkey foreign KEY (research_center) references research_centers (id)
) TABLESPACE pg_default;

create table public.authors (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  full_name text not null,
  email text null,
  first_name_initial text null,
  last_name text null,
  constraint authors_pkey primary key (id)
) TABLESPACE pg_default;

create table public.research_centers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  institution text null,
  city character varying null,
  state character varying null,
  zip character varying null,
  constraint research_centers_pkey primary key (id)
) TABLESPACE pg_default;